config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'images#index'

  namespace :api do
    resources :images, only: [:update]
  end

  resources :folders
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/folder.rb
# frozen_string_literal: true

class Folder < ApplicationRecord
  validates :title, presence: true
  validates :description, presence: true
end

app/models/image.rb
# frozen_string_literal: true

class Image < ApplicationRecord
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
end

app/controllers/api/images_controller.rb
# frozen_string_literal: true

module Api
  class ImagesController < ApplicationController
    def update
      @image = Image.find(params[:id])

      @image.update! title: params[:image][:title].strip

      head :ok
    end
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/folders_controller.rb
# frozen_string_literal: true

class FoldersController < ApplicationController
  before_action :resource_folder, only: %i[edit update new index]

  def index
    render locals: { folders: Folder.order(created_at: :desc), folder: resource_folder }
  end

  def create
    if resource_folder.save
      redirect_to folders_path
    else
      render :new, locals: { folder: resource_folder }
    end
  end

  def edit
    render locals: { folder: resource_folder }
  end

  def new
    render locals: { folder: resource_folder }
  end

  def update
    if resource_folder.update folder_params
      redirect_to folders_path
    else
      render :edit, locals: { folder: resource_folder }
    end
  end

  def resource_folder
    @resource_folder ||= params[:id] ? Folder.find(params[:id]) : Folder.new(folder_params)
  end

  def folder_params
    (params[:folder] || ActionController::Parameters.new).permit(:title, :description)
  end
end

app/controllers/images_controller.rb
# frozen_string_literal: true

class ImagesController < ApplicationController
  def index
    render locals: { images: Image.all }
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/images_helper.rb
# frozen_string_literal: true

module ImagesHelper
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/views/folders/_folder.html.erb
<%= turbo_frame_tag folder do %>
<section class="mb-4">
  <h2><%= folder.title %></h2>

  <p><%= folder.description %></p>
  <p><%= link_to 'Edit', edit_folder_path(folder), class: 'btn btn-primary' %></p>
</section>
<% end %>

app/views/folders/_form.html.erb
<%= turbo_frame_tag folder do %>
<%= form_with model: folder do |f| %>
  <%= render 'shared/errors', object: folder %>

  <div class="mb-3 row">
    <div class="col-sm-2 col-form-label">
      <%= f.label :title %>
    </div>

    <div class="col-sm-10">
      <%= f.text_field :title, class: 'form-control' %>
    </div>
  </div>

  <div class="mb-3 row">
    <div class="col-sm-2 col-form-label">
      <%= f.label :description %>
    </div>

    <div class="col-sm-10">
      <%= f.text_area :description, class: 'form-control' %>
    </div>
  </div>

  <%= f.submit 'Submit', class: 'btn btn-primary' %>
<% end %>
<% end %>

app/views/folders/edit.html.erb
<h1>Edit folder</h1>
<%= render 'form', folder: folder %>

app/views/folders/index.html.erb
<h1>Folders</h1>

<%= turbo_frame_tag folder do %>
 <%= link_to 'Add folder', new_folder_path, class: 'btn btn-primary' %>
<% end %>

<%= render folders %>

app/views/folders/new.html.erb
<h1>New folder</h1>

<%= render 'form', folder: folder %>

app/views/images/index.html.erb
<h1>Images: </h1>

<% images.each do |image| %>
  <%= tag.section class: 'my-5',
                  data: { controller: 'images toast',
                          action: 'images:copy->toast#show',
                          'images-loading-class': 'disabled',
                          'images-id-value': image.id } do  %>
    <%= image_tag image.url, class: 'img-thumbnail rounded d-block',
                  alt: image.title,
                  data: { 'action': 'click->images#getUrl', 'images-target': 'image' } %>
  <% end %>
<% end %>


<div class="toast-container position-fixed bottom-0 end-0 p-3">
  <div id="copyToast" class="toast">
    <div class="toast-header">
      <strong class="me-auto">Hey!</strong>
      <button type="button" class="btn-close" data-bs-dismiss="toast"></button>
    </div>
    <div class="toast-body">Text</div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HotwireApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
  <main class="container ">
    <%= yield %>
  </main>
  </body>
</html>

app/views/shared/_errors.html.erb
<% if object&.errors&.full_messages&.any? %>
  <div class="alert alert-danger">
    <ul class="mb-0">
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>